image:
  file: .docker/gitpod/mathlib/Dockerfile

vscode:
  extensions:
    - jroesch.lean

tasks:
  # if getting the cache for the current commit fails, try the closest common ancestor between this branch and master
  - command: . /home/gitpod/.profile && (leanproject get-mathlib-cache || leanproject get-cache --rev $(git merge-base origin/master HEAD))
